@isTest
private class QueueEventNamesTest {
	
	@isTest public static void test_method_one() {
		// Implement test code
		
		String a = QueueEventNames.MKTPLACE_CASE_OPEN_GIBA_TO_SALESFORCE.name();
	

	
		QueueEventNames b = QueueEventNames.MKTPLACE_CASE_COMMENT_TO_SALESFORCE;
	

	
		QueueEventNames c = QueueEventNames.MKTPLACE_CASE_COMMENT_SALESFORCE_TO_GIBA;
	

		QueueEventNames d = QueueEventNames.MKTPLACE_CASE_CLOSE_GIBA_TO_SALESFORCE;
	

		
		QueueEventNames e = QueueEventNames.MKTPLACE_CASE_CLOSE_SALESFORCE_TO_GIBA;
		
	}


	
}